version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P ${DB_DOCKER_PORT} -u ${DB_USER} -p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: book_store
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:${DB_DOCKER_PORT}/${DB_DATABASE}?serverTimezone=UTC",
      "spring.datasource.username": "${DB_USER}", 
      "spring.datasource.password": "${DB_PASSWORD}", 
      "jwt.secret": "${JWT_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
